### PR TITLE
Fix problems on PHPStan Level 0-4

### PR DESCRIPTION
**Pull request by szepeviktor**
Hello @sabrina-zeidan!

Please consider using @phpstan

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
#    bootstrapFiles:
#        - tests/phpstan/bootstrap.php
    scanFiles:
        - ./includes/class-speedguard-deactivator.php
        - ./includes/class-speedguard-activator.php
        - ./includes/class-speedguard-i18n.php
        - ./includes/class-speedguard.php
        - ./includes/class-speedguard-loader.php
        - ./public/partials/speedguard-public-display.php
        - ./public/class-speedguard-public.php
        - ./uninstall.php
        - ./admin/partials/speedguard-admin-display.php
        - ./admin/class-speedguard-admin.php
        - ./admin/includes/class.tests.php
        - ./admin/includes/class.settings.php
        - ./admin/includes/class.widgets.php
        - ./admin/includes/class.notifications.php
        - ./admin/includes/class.lighthouse.php
        - ./speedguard.php
    paths:
        - speedguard.php
        - uninstall.php
        - includes/
        - admin/
        - public/
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
There are 4 more var_dump-s

```
admin/includes/class.tests.php:92:                      var_dump($guarded_page_url);
admin/includes/class.tests.php:94:                      var_dump($guarded_page_type);
admin/includes/class.tests.php:96:                      var_dump($guarded_post_id);
admin/includes/class.tests.php:100:                     var_dump($speedguard_on);
```

**Comment by szepeviktor** [comment]
You can use PHPCS' `Squiz.PHP.DiscouragedFunctions` sniff to catch them.

**Comment by sabrina-zeidan** [comment]
Hi @szepeviktor! Thank you, I'll check it out! This is a good reading too https://github.com/szepeviktor/phpstan-wordpress#make-your-code-testable Cheers!

**Comment by szepeviktor** [comment]
[type juggling](https://www.php.net/manual/en/language.types.type-juggling.php): `$a = '15'; if ($a) ...`

...has been added to "bad parts"

**Pull request closed without merging**
